import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:flutter/material.dart';

List<IconData> depenseIcons = [
  FontAwesomeIcons.car,
  FontAwesomeIcons.house,
  FontAwesomeIcons.utensils,
  FontAwesomeIcons.heart,
  FontAwesomeIcons.paw,
  FontAwesomeIcons.bolt,
  FontAwesomeIcons.book,
  FontAwesomeIcons.briefcase,
  FontAwesomeIcons.bus,
  FontAwesomeIcons.plane,
  FontAwesomeIcons.creditCard, //
  FontAwesomeIcons.bed,
  FontAwesomeIcons.dumbbell,
  FontAwesomeIcons.fileInvoiceDollar,
  FontAwesomeIcons.gasPump, //
  FontAwesomeIcons.graduationCap,
  FontAwesomeIcons.mortarPestle,
  FontAwesomeIcons.music,
  FontAwesomeIcons.paperPlane,
  FontAwesomeIcons.phone,
  FontAwesomeIcons.snowflake,
  FontAwesomeIcons.smoking,
  FontAwesomeIcons.spa,
  FontAwesomeIcons.suitcase,
  FontAwesomeIcons.sun,
  FontAwesomeIcons.taxi,
  FontAwesomeIcons.train,
  FontAwesomeIcons.tree,
  FontAwesomeIcons.tv,
  FontAwesomeIcons.wineBottle,
  FontAwesomeIcons.wallet,
  FontAwesomeIcons.video,
];

Map<IconData, String> iconNames = {
  FontAwesomeIcons.car: 'car',
  FontAwesomeIcons.house: 'house',
  FontAwesomeIcons.utensils: 'utensils',
  FontAwesomeIcons.heart: 'heart',
  FontAwesomeIcons.paw: 'paw',
  FontAwesomeIcons.bolt: 'bolt',
  FontAwesomeIcons.book: 'book',
  FontAwesomeIcons.briefcase: 'briefcase',
  FontAwesomeIcons.bus: 'bus',
  FontAwesomeIcons.plane: 'plane',
  FontAwesomeIcons.creditCard: 'credit_card',
  FontAwesomeIcons.bed: 'bed',
  FontAwesomeIcons.dumbbell: 'dumbbell',
  FontAwesomeIcons.fileInvoiceDollar: 'file_invoice_dollar',
  FontAwesomeIcons.gasPump: 'gas_pump', //
  FontAwesomeIcons.graduationCap: 'graduation_cap',
  FontAwesomeIcons.mortarPestle: 'mortar_pestle',
  FontAwesomeIcons.music: 'music',
  FontAwesomeIcons.paperPlane: 'paper_plane',
  FontAwesomeIcons.phone: 'phone',
  FontAwesomeIcons.snowflake: 'snowflake',
  FontAwesomeIcons.smoking: 'smoking',
  FontAwesomeIcons.spa: 'spa',
  FontAwesomeIcons.suitcase: 'suitcase',
  FontAwesomeIcons.sun: 'sun',
  FontAwesomeIcons.taxi: 'taxi',
  FontAwesomeIcons.train: 'train',
  FontAwesomeIcons.tree: 'tree',
  FontAwesomeIcons.tv: 'tv',
  FontAwesomeIcons.wineBottle: 'wine_bottle',
  FontAwesomeIcons.wallet: 'wallet',
  FontAwesomeIcons.video: 'video',
};

final icons = {
  'car': FontAwesomeIcons.car,
  'house': FontAwesomeIcons.house,
  'utensils': FontAwesomeIcons.utensils,
  'heart': FontAwesomeIcons.heart,
  'paw': FontAwesomeIcons.paw,
  'bolt': FontAwesomeIcons.bolt,
  'book': FontAwesomeIcons.book,
  'briefcase': FontAwesomeIcons.briefcase,
  'bus': FontAwesomeIcons.bus,
  'plane': FontAwesomeIcons.plane,
  'creditCard': FontAwesomeIcons.creditCard,
  'bed': FontAwesomeIcons.bed,
  'dumbbell': FontAwesomeIcons.dumbbell,
  'fileInvoiceDollar': FontAwesomeIcons.fileInvoiceDollar,
  'gasPump': FontAwesomeIcons.gasPump,
  'graduationCap': FontAwesomeIcons.graduationCap,
  'mortarPestle': FontAwesomeIcons.mortarPestle,
  'music': FontAwesomeIcons.music,
  'paperPlane': FontAwesomeIcons.paperPlane,
  'phone': FontAwesomeIcons.phone,
  'snowflake': FontAwesomeIcons.snowflake,
  'smoking': FontAwesomeIcons.smoking,
  'spa': FontAwesomeIcons.spa,
  'suitcase': FontAwesomeIcons.suitcase,
  'sun': FontAwesomeIcons.sun,
  'taxi': FontAwesomeIcons.taxi,
  'train': FontAwesomeIcons.train,
  'tree': FontAwesomeIcons.tree,
  'tv': FontAwesomeIcons.tv,
  'wine_bottle': FontAwesomeIcons.wineBottle,
  'wallet': FontAwesomeIcons.wallet,
  'video': FontAwesomeIcons.video,
};
